timezone: Europe/Rome
baseurl: /pri
permalink: pretty
remote_theme: giovian/ui@main

sidebar: []
footer: true
nav: true
navigation: []

defaults:
  -
    scope:
      type: 'posts'
    values:
      pagination: true
      metadata: true